# Generated by Django 5.2.11 on 2026-02-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="placement_height",
            field=models.PositiveIntegerField(
                default=1, help_text="Высота (в ячейках 10x10)"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="placement_width",
            field=models.PositiveIntegerField(
                default=1, help_text="Ширина (в ячейках 10x10)"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="placement_x",
            field=models.PositiveIntegerField(
                default=0, help_text="X (в ячейках 10x10) от левого края"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="placement_y",
            field=models.PositiveIntegerField(
                default=0, help_text="Y (в ячейках 10x10) от верхнего края"
            ),
        ),
        migrations.AddField(
            model_name="pixelorder",
            name="placement_height",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="pixelorder",
            name="placement_width",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="pixelorder",
            name="placement_x",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pixelorder",
            name="placement_y",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pixelorder",
            name="telegram_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pixelorder",
            name="telegram_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pixelorder",
            name="telegram_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
